server:
  port: 8501

spring:
  application:
    name: account-service
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true

spcloud:
  cassandra:
    contact:
      point: localhost
    port: 9042
    keyspace:
      name: springcloud

    username: cassandra
    password: cassandra
